[package]
name = "wash"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = { version = "1.0.56", features = ["std"], default-features = false }
camino = { version = "1.1.1", default-features = false }
